import 'package:equatable/equatable.dart';

import 'package:omni_runner/domain/entities/evolution_metric_entity.dart';

/// Direction of an athlete's performance trend.
///
/// Append-only ordinal rule (DECISAO 018): new values at the end only.
enum TrendDirection {
  /// Metric is moving in a favorable direction.
  /// For pace: getting lower. For volume/frequency: getting higher.
  improving,

  /// No significant change (within ±5% threshold).
  stable,

  /// Metric is moving in an unfavorable direction.
  declining,

  /// Not enough data to determine a trend.
  insufficient,
}

/// Result of a temporal trend analysis for one athlete and one metric.
///
/// Compares the athlete's recent performance against their [baselineValue],
/// producing a [direction] and [changePercent].
///
/// Generated by the Evolution Analytics Engine. One trend per
/// (userId, groupId, metric, period) — upserted when recalculated.
///
/// Immutable value object. See Phase 16 — Evolution Analytics Engine.
final class AthleteTrendEntity extends Equatable {
  /// Unique identifier (UUID v4).
  final String id;

  final String userId;

  /// Coaching group context.
  final String groupId;

  final EvolutionMetric metric;
  final EvolutionPeriod period;

  final TrendDirection direction;

  /// Most recent aggregated value for this metric.
  final double currentValue;

  /// Reference value from the baseline snapshot.
  final double baselineValue;

  /// Signed percentage change: `(current - baseline) / baseline * 100`.
  /// Positive = increased, negative = decreased.
  /// For [EvolutionMetric.avgPace], negative means faster (improving).
  final double changePercent;

  /// Number of data points (periods) used in the trend analysis.
  final int dataPoints;

  /// Human-readable period key of the latest data point, e.g. "2026-W08".
  final String latestPeriodKey;

  /// When this trend was computed (ms since epoch, UTC).
  final int analyzedAtMs;

  const AthleteTrendEntity({
    required this.id,
    required this.userId,
    required this.groupId,
    required this.metric,
    required this.period,
    required this.direction,
    required this.currentValue,
    required this.baselineValue,
    required this.changePercent,
    required this.dataPoints,
    required this.latestPeriodKey,
    required this.analyzedAtMs,
  });

  /// Whether the trend has enough data to be actionable.
  bool get isActionable =>
      direction != TrendDirection.insufficient && dataPoints >= 2;

  /// Absolute magnitude of change (always positive).
  double get absoluteChange => changePercent.abs();

  /// Whether [metric] improves when its value decreases (e.g. pace).
  bool get isLowerBetter => metric == EvolutionMetric.avgPace;

  @override
  List<Object?> get props => [
        id,
        userId,
        groupId,
        metric,
        period,
        direction,
        currentValue,
        baselineValue,
        changePercent,
        dataPoints,
        latestPeriodKey,
        analyzedAtMs,
      ];
}
