-- ============================================================================
-- Omni Runner — Persistent invite codes for coaching groups
-- Date: 2026-02-25
-- Sprint: 19.2.1
-- Origin: MICRO-PASSO 19.2.1 — Criar Invite Links Persistentes
-- ============================================================================
-- Adds invite_code to coaching_groups for shareable join links:
--   https://omnirunner.app/invite/{invite_code}
--
-- Design: invite_code lives on the GROUP, not on coaching_invites.
-- coaching_invites remains for user-to-user direct invitations.
-- The invite_code is a group-level, reusable, shareable short code.
-- ============================================================================

BEGIN;

-- ── 1. Helper: generate short alphanumeric invite code ─────────────────────
-- 8-char code from base36 (0-9, A-Z). Collision-resistant with retry loop.

CREATE OR REPLACE FUNCTION public.fn_generate_invite_code(p_length INT DEFAULT 8)
RETURNS TEXT AS $$
DECLARE
  v_chars TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  v_code  TEXT := '';
  v_i     INT;
BEGIN
  FOR v_i IN 1..p_length LOOP
    v_code := v_code || substr(v_chars, floor(random() * length(v_chars) + 1)::INT, 1);
  END LOOP;
  RETURN v_code;
END;
$$ LANGUAGE plpgsql VOLATILE;

-- ── 2. Add columns to coaching_groups ──────────────────────────────────────

ALTER TABLE public.coaching_groups
  ADD COLUMN IF NOT EXISTS invite_code    TEXT,
  ADD COLUMN IF NOT EXISTS invite_enabled BOOLEAN NOT NULL DEFAULT TRUE;

-- ── 3. Unique index for fast lookup ────────────────────────────────────────

CREATE UNIQUE INDEX IF NOT EXISTS idx_coaching_groups_invite_code
  ON public.coaching_groups (invite_code)
  WHERE invite_code IS NOT NULL;

-- ── 4. Backfill existing groups with unique codes ──────────────────────────

DO $$
DECLARE
  r RECORD;
  v_code TEXT;
  v_attempts INT;
BEGIN
  FOR r IN SELECT id FROM public.coaching_groups WHERE invite_code IS NULL LOOP
    v_attempts := 0;
    LOOP
      v_code := public.fn_generate_invite_code(8);
      BEGIN
        UPDATE public.coaching_groups SET invite_code = v_code WHERE id = r.id;
        EXIT;
      EXCEPTION WHEN unique_violation THEN
        v_attempts := v_attempts + 1;
        IF v_attempts > 10 THEN
          RAISE EXCEPTION 'Failed to generate unique invite code after 10 attempts';
        END IF;
      END;
    END LOOP;
  END LOOP;
END $$;

-- ── 5. Make invite_code NOT NULL after backfill ────────────────────────────

ALTER TABLE public.coaching_groups
  ALTER COLUMN invite_code SET NOT NULL;

-- ── 6. Default for new rows: auto-generate on insert ───────────────────────

ALTER TABLE public.coaching_groups
  ALTER COLUMN invite_code SET DEFAULT public.fn_generate_invite_code(8);

-- ── 7. RPC: lookup group by invite code ────────────────────────────────────
-- SECURITY DEFINER: any authenticated user can look up a group by code
-- (needed during onboarding when user has no group membership yet).

CREATE OR REPLACE FUNCTION public.fn_lookup_group_by_invite_code(p_code TEXT)
RETURNS TABLE (
  id                 UUID,
  name               TEXT,
  logo_url           TEXT,
  city               TEXT,
  coach_display_name TEXT,
  member_count       BIGINT,
  invite_enabled     BOOLEAN
) AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'NOT_AUTHENTICATED';
  END IF;

  IF p_code IS NULL OR length(trim(p_code)) < 3 THEN
    RAISE EXCEPTION 'INVALID_CODE';
  END IF;

  RETURN QUERY
  SELECT
    g.id,
    g.name,
    g.logo_url,
    g.city,
    COALESCE(p.display_name, 'Coach') AS coach_display_name,
    (SELECT count(*) FROM public.coaching_members cm WHERE cm.group_id = g.id) AS member_count,
    g.invite_enabled
  FROM public.coaching_groups g
  LEFT JOIN public.profiles p ON p.id = g.coach_user_id
  WHERE upper(trim(g.invite_code)) = upper(trim(p_code))
    AND g.invite_enabled = TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ── 8. Update fn_create_assessoria to return invite_code ───────────────────
-- The invite_code is auto-generated by the DEFAULT, so we just need to
-- include it in the return value.

CREATE OR REPLACE FUNCTION public.fn_create_assessoria(
  p_name TEXT,
  p_city TEXT DEFAULT ''
)
RETURNS JSONB AS $$
DECLARE
  v_uid          UUID;
  v_display_name TEXT;
  v_group_id     UUID;
  v_invite_code  TEXT;
  v_now_ms       BIGINT;
BEGIN
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'NOT_AUTHENTICATED';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = v_uid AND user_role = 'ASSESSORIA_STAFF'
  ) THEN
    RAISE EXCEPTION 'NOT_STAFF';
  END IF;

  IF length(trim(p_name)) < 3 OR length(trim(p_name)) > 80 THEN
    RAISE EXCEPTION 'INVALID_NAME';
  END IF;

  SELECT display_name INTO v_display_name
    FROM public.profiles WHERE id = v_uid;

  v_group_id := gen_random_uuid();
  v_now_ms   := EXTRACT(EPOCH FROM now())::BIGINT * 1000;

  INSERT INTO public.coaching_groups (id, name, coach_user_id, city)
  VALUES (v_group_id, trim(p_name), v_uid, COALESCE(trim(p_city), ''))
  RETURNING invite_code INTO v_invite_code;

  INSERT INTO public.coaching_members (user_id, group_id, display_name, role, joined_at_ms)
  VALUES (v_uid, v_group_id, COALESCE(v_display_name, 'Coach'), 'admin_master', v_now_ms);

  UPDATE public.profiles
    SET active_coaching_group_id = v_group_id, updated_at = now()
    WHERE id = v_uid;

  RETURN jsonb_build_object(
    'status', 'created',
    'group_id', v_group_id,
    'invite_code', v_invite_code,
    'invite_link', 'https://omnirunner.app/invite/' || v_invite_code
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMIT;
